# Generated by Django 2.2.15 on 2020-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Texts',
                'ordering': ['id'],
            },
        ),
    ]
