# Generated by Django 2.2.15 on 2020-09-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinnecta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texts',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
